In [2]:
import pandas as pd

In [24]:
df = pd.read_csv('Base_Melodia.csv')
display(df)

,sort_name,clean_name,album,rank_2003,rank_2012,rank_2020,differential,release_year,genre,type,...,peak_billboard_position,spotify_popularity,spotify_url,artist_member_count,artist_gender,artist_birth_year_sum,debut_album_release_year,ave_age_at_top_500,years_between,album_id
0,"Sinatra, Frank",Frank Sinatra,In the Wee Small Hours,100.0,101.0,282.0,-182,1955,Big Band/Jazz,Studio,...,2,48.0,spotify:album:3GmwKB1tgPZgXeRJZSm9WX,1.0,Male,1915.0,1946.0,40.000000,9.0,3GmwKB1tgPZgXeRJZSm9WX
1,"Diddley, Bo",Bo Diddley,Bo Diddley / Go Bo Diddley,214.0,216.0,455.0,-241,1955,Rock n' Roll/Rhythm & Blues,Studio,...,201,50.0,spotify:album:1cbtDEwxCjMhglb49OgNBR,1.0,Male,1928.0,1955.0,27.000000,0.0,1cbtDEwxCjMhglb49OgNBR
2,"Presley, Elvis",Elvis Presley,Elvis Presley,55.0,56.0,332.0,-277,1956,Rock n' Roll/Rhythm & Blues,Studio,...,1,58.0,spotify:album:7GXP5OhYyPVLmcVfO9Iqin,1.0,Male,1935.0,1956.0,21.000000,0.0,7GXP5OhYyPVLmcVfO9Iqin
3,"Sinatra, Frank",Frank Sinatra,Songs for Swingin' Lovers!,306.0,308.0,NaN,-195,1956,Big Band/Jazz,Studio,...,2,62.0,spotify:album:4kca7vXd1Wo5GE2DMafvMc,1.0,Male,1915.0,1946.0,41.000000,10.0,4kca7vXd1Wo5GE2DMafvMc
4,Little Richard,Little Richard,Here's Little Richard,50.0,50.0,227.0,-177,1957,NaN,Studio,...,13,64.0,spotify:album:18tV6PLXYvVjsdOVk0S7M8,1.0,Male,1932.0,1957.0,25.000000,0.0,18tV6PLXYvVjsdOVk0S7M8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,Beck,Beck,Sea Change,440.0,436.0,NaN,-61,2002,Indie/Alternative Rock,Studio,...,8,51.0,spotify:album:5ieP11rJQvuYz0Ov3k03cy,1.0,Male,1970.0,1993.0,32.000000,9.0,5ieP11rJQvuYz0Ov3k03cy
687,"Cooke, Sam",Sam Cooke,Portrait of a Legend 1951-1964,106.0,107.0,307.0,-201,2003,Soul/Gospel/R&B,Greatest Hits,...,135,55.0,spotify:album:4jiO2jRz7g50ESvYYKsKwZ,1.0,Male,1931.0,1958.0,72.000000,45.0,4jiO2jRz7g50ESvYYKsKwZ
688,White Stripes,The White Stripes,Elephant,390.0,390.0,449.0,-59,2003,Blues/Blues Rock,Studio,...,6,76.0,spotify:album:6D9urpsOWWKtYvF6PaorGE,2.0,Male/Female,3949.0,1999.0,28.500000,4.0,6D9urpsOWWKtYvF6PaorGE
689,"Chao, Manu",Manu Chao,Proxima estacion: Esperanza,NaN,474.0,NaN,-501,2001,Latin,Studio,...,201,73.0,spotify:album:4t1LLdXiWTfoywqricztFo,1.0,Male,1961.0,1998.0,40.000000,3.0,4t1LLdXiWTfoywqricztFo
690,Beach Boys,The Beach Boys,The Smile Sessions,NaN,381.0,NaN,-501,2011,NaN,Compilation,...,201,41.0,spotify:album:01TG7VOg4F90jXv3a1yCgA,6.0,Male,11657.0,1962.0,68.166667,49.0,01TG7VOg4F90jXv3a1yCgA

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691 entries, 0 to 690
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   sort_name                 691 non-null    object
 1   clean_name                691 non-null    object
 2   album                     691 non-null    object
 3   rank_2003                 500 non-null    float64
 4   rank_2012                 500 non-null    float64
 5   rank_2020                 500 non-null    float64
 6   differential              691 non-null    int64
 7   release_year              691 non-null    int64
 8   genre                     527 non-null    object
 9   type                      691 non-null    object
 10  weeks_on_billboard        572 non-null    float64
 11  peak_billboard_position   691 non-null    int64
 12  spotify_popularity        654 non-null    float64
 13  spotify_url               655 non-null    object
 14  artist_member_count       686 non-null    float64
 15  artist_gender             686 non-null    object
 16  artist_birth_year_sum     686 non-null    float64
 17  debut_album_release_year  686 non-null    float64
 18  ave_age_at_top_500        686 non-null    float64
 19  years_between             686 non-null    float64
 20  album_id                  691 non-null    object
dtypes: float64(10), int64(3), object(8)
memory usage: 113.5+ KB

In [26]:
df = df.drop("spotify_url",axis=1)
df = df.drop("album_id",axis=1)
display(df)

,sort_name,clean_name,album,rank_2003,rank_2012,rank_2020,differential,release_year,genre,type,weeks_on_billboard,peak_billboard_position,spotify_popularity,artist_member_count,artist_gender,artist_birth_year_sum,debut_album_release_year,ave_age_at_top_500,years_between
0,"Sinatra, Frank",Frank Sinatra,In the Wee Small Hours,100.0,101.0,282.0,-182,1955,Big Band/Jazz,Studio,14.0,2,48.0,1.0,Male,1915.0,1946.0,40.000000,9.0
1,"Diddley, Bo",Bo Diddley,Bo Diddley / Go Bo Diddley,214.0,216.0,455.0,-241,1955,Rock n' Roll/Rhythm & Blues,Studio,NaN,201,50.0,1.0,Male,1928.0,1955.0,27.000000,0.0
2,"Presley, Elvis",Elvis Presley,Elvis Presley,55.0,56.0,332.0,-277,1956,Rock n' Roll/Rhythm & Blues,Studio,100.0,1,58.0,1.0,Male,1935.0,1956.0,21.000000,0.0
3,"Sinatra, Frank",Frank Sinatra,Songs for Swingin' Lovers!,306.0,308.0,NaN,-195,1956,Big Band/Jazz,Studio,NaN,2,62.0,1.0,Male,1915.0,1946.0,41.000000,10.0
4,Little Richard,Little Richard,Here's Little Richard,50.0,50.0,227.0,-177,1957,NaN,Studio,5.0,13,64.0,1.0,Male,1932.0,1957.0,25.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,Beck,Beck,Sea Change,440.0,436.0,NaN,-61,2002,Indie/Alternative Rock,Studio,26.0,8,51.0,1.0,Male,1970.0,1993.0,32.000000,9.0
687,"Cooke, Sam",Sam Cooke,Portrait of a Legend 1951-1964,106.0,107.0,307.0,-201,2003,Soul/Gospel/R&B,Greatest Hits,1.0,135,55.0,1.0,Male,1931.0,1958.0,72.000000,45.0
688,White Stripes,The White Stripes,Elephant,390.0,390.0,449.0,-59,2003,Blues/Blues Rock,Studio,57.0,6,76.0,2.0,Male/Female,3949.0,1999.0,28.500000,4.0
689,"Chao, Manu",Manu Chao,Proxima estacion: Esperanza,NaN,474.0,NaN,-501,2001,Latin,Studio,NaN,201,73.0,1.0,Male,1961.0,1998.0,40.000000,3.0
690,Beach Boys,The Beach Boys,The Smile Sessions,NaN,381.0,NaN,-501,2011,NaN,Compilation,NaN,201,41.0,6.0,Male,11657.0,1962.0,68.166667,49.0

Colunas:

Clean_name: nome do artista

Album: título do álbum

Rank_2003: posição que o álbum ocupava no ranking de álbuns em 2003

Rank_2012: posição que o álbum ocupava no ranking de álbuns em 2012

Rank_2020: posição que o álbum ocupava no ranking de álbuns em 2020

Differential: a diferença entre o rank de 2003 e 2020, que é negativa se o álbum subiu de posição ao longo dos anos e positiva se desceu

Release_year: ano em que o álbum foi lançado

Genre: gênero musical do álbum 

Type: tipo de álbum, como um álbum de estúdio, uma compilação, uma trilha sonora ou um álbum ao vivo

Weeks_on_billboard: número de semanas que o álbum passou na Billboard 200, que mede o desempenho dos álbuns em termos de vendas e popularidade

Peak_billboard_position: posição mais alta que o álbum alcançou na Billboard 200, que indica o pico de popularidade do álbum

Spotify_popularity: medida de popularidade do álbum no Spotify

Artist_member_count: número de integrantes do grupo musical (para artistas solo, esse valor é 1)

Artist_gender: gênero dos membros do grupo ou do artista solo

Artist_birth_year_sum: soma dos anos de nascimento de todos os membros do grupo ou, no caso de um artista solo, o ano de nascimento desse artista. Esse valor pode ser usado para calcular a idade média dos membros.

Debut_album_release_year: ano em que o artista ou banda lançou seu álbum de estreia

Ave_age_at_top_500: idade média dos membros do grupo (ou do artista solo) no momento em que o álbum foi incluído em uma lista de "Top 500" álbuns

Years_between: diferença entre o ano de lançamento do álbum de estreia do artista e o e o ano em que o álbum foi listado no "Top 500"

In [27]:
df.describe()

,rank_2003,rank_2012,rank_2020,differential,release_year,weeks_on_billboard,peak_billboard_position,spotify_popularity,artist_member_count,artist_birth_year_sum,debut_album_release_year,ave_age_at_top_500,years_between
count,500.000000,500.000000,500.000000,691.000000,691.000000,572.000000,691.000000,654.000000,686.000000,686.000000,686.000000,686.000000,686.000000
mean,250.504000,250.500000,250.500000,-12.322721,1982.872648,64.270979,61.193922,55.805810,2.746356,5363.214286,1976.871720,29.609107,5.928571
std,144.486063,144.481833,144.481833,199.041031,14.554784,75.141513,77.156551,14.948525,2.023174,3947.127116,14.958566,9.348495,8.420647
min,1.000000,1.000000,1.000000,-501.000000,1955.000000,1.000000,1.000000,10.000000,1.000000,1910.000000,1934.000000,17.000000,0.000000
25%,125.750000,125.750000,125.750000,-137.500000,1971.000000,20.750000,2.000000,46.000000,1.000000,1948.000000,1966.250000,24.041667,1.000000
50%,250.500000,250.500000,250.500000,-8.000000,1979.000000,44.500000,17.000000,57.000000,2.000000,3896.000000,1973.000000,27.000000,3.000000
75%,375.250000,375.250000,375.250000,106.000000,1994.000000,81.000000,111.500000,68.000000,4.000000,7845.000000,1989.000000,31.000000,7.000000
max,500.000000,500.000000,500.000000,484.000000,2019.000000,741.000000,201.000000,91.000000,12.000000,23368.000000,2019.000000,88.000000,54.000000